# Conexiones locales dentro del contenedor
local   all             all                                     trust

# Conexiones TCP para clientes del entorno de laboratorio
host    all             all             0.0.0.0/0               scram-sha-256

# Acceso para replicación usando el usuario admin
# En esta primera versión se reutiliza el superusuario creado por la imagen
host    replication     admin            0.0.0.0/0              scram-sha-256