services:
  postgres-primary:
    image: postgres:15
    container_name: postgres-primary
    environment:
      POSTGRES_DB: social_network
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=trust"
    ports:
      - "5432:5432"
    volumes:
      - postgres_primary_data:/var/lib/postgresql/data
      - ../scripts/postgres/01-init-primary.sql:/docker-entrypoint-initdb.d/01-init-primary.sql:ro
      - ./postgres/00-configure-primary.sh:/docker-entrypoint-initdb.d/00-configure-primary.sh:ro
    command:
      - postgres
      - -c
      - listen_addresses=*
      - -c
      - wal_level=replica
      - -c
      - max_wal_senders=10
      - -c
      - max_replication_slots=10
      - -c
      - max_prepared_transactions=100
      - -c
      - hot_standby=on
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d social_network" ]
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - social_network

  postgres-replica-1:
    image: postgres:15
    container_name: postgres-replica-1
    environment:
      PGDATA: /var/lib/postgresql/data
      REPLICATION_USER: replicator
      REPLICATION_PASSWORD: replicator123
      REPLICATION_SLOT: replica1_slot
      REPLICATION_NAME: postgres-replica-1
    ports:
      - "5433:5432"
    volumes:
      - postgres_replica1_data:/var/lib/postgresql/data
      - ./postgres/init-replica.sh:/usr/local/bin/init-replica.sh:ro
    entrypoint: [ "/bin/bash", "/usr/local/bin/init-replica.sh" ]
    depends_on:
      postgres-primary:
        condition: service_healthy
    networks:
      - social_network

  postgres-replica-2:
    image: postgres:15
    container_name: postgres-replica-2
    environment:
      PGDATA: /var/lib/postgresql/data
      REPLICATION_USER: replicator
      REPLICATION_PASSWORD: replicator123
      REPLICATION_SLOT: replica2_slot
      REPLICATION_NAME: postgres-replica-2
    ports:
      - "5434:5432"
    volumes:
      - postgres_replica2_data:/var/lib/postgresql/data
      - ./postgres/init-replica.sh:/usr/local/bin/init-replica.sh:ro
    entrypoint: [ "/bin/bash", "/usr/local/bin/init-replica.sh" ]
    depends_on:
      postgres-primary:
        condition: service_healthy
    networks:
      - social_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres-primary
    networks:
      - social_network

volumes:
  postgres_primary_data:
  postgres_replica1_data:
  postgres_replica2_data:


networks:
  social_network:
    driver: bridge
